version: '3.1'


services:
   angular-frontend:
      image: cagejsn/pokerfrontend:latest
      ports:
        - "4200:4200"
   go-backend:
      image: cagejsn/pokerengine:latest
      deploy:
         restart_policy:
            condition: on-failure
      ports:
        - "8090:8090"
   db:
      image: mysql
      restart: always
      environment:
         MYSQL_ROOT_PASSWORD: "example"
         MYSQL_USER: "cagejsn"
         MYSQL_PASSWORD: "password"
         MYSQL_DATABASE: "pokerdb"
      ports:
        - "3306:3306"
